spring.application.name=eventia-tfg
server.port=8090

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# desactivar data.sql
#spring.sql.init.mode=never

# iniciar con data.sql
spring.sql.init.mode=always

spring.datasource.url=jdbc:mariadb://localhost:3313/eventia_tfg_db
spring.datasource.username=eventia_tfg_user
spring.datasource.password=eventia_tfg_pass
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect